//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_WareDetails
    {
        public Spl_WareDetails()
        {
            this.Spl_WarehouseWarrantDetails = new HashSet<Spl_WarehouseWarrantDetails>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string BarCode { get; set; }
        public string WareCategoryId { get; set; }
        public string Unit { get; set; }
        public string Lable { get; set; }
        public Nullable<decimal> BuyPrice { get; set; }
        public decimal SalePrice { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public string Remark { get; set; }
        public string Vender { get; set; }
        public string Brand { get; set; }
        public string Color { get; set; }
        public string Material { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
        public string ComeFrom { get; set; }
        public Nullable<decimal> UpperLimit { get; set; }
        public Nullable<decimal> LowerLimit { get; set; }
        public Nullable<decimal> PrimeCost { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Price4 { get; set; }
        public Nullable<decimal> Price5 { get; set; }
        public string Photo1 { get; set; }
        public string Photo2 { get; set; }
        public string Photo3 { get; set; }
        public string Photo4 { get; set; }
        public string Photo5 { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual Spl_WareCategory Spl_WareCategory { get; set; }
        public virtual ICollection<Spl_WarehouseWarrantDetails> Spl_WarehouseWarrantDetails { get; set; }
    }
}
