//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spl_Warehouse
    {
        public Spl_Warehouse()
        {
            this.Spl_WarehouseWarrantDetails = new HashSet<Spl_WarehouseWarrantDetails>();
            this.Spl_WarehouseWarrant = new HashSet<Spl_WarehouseWarrant>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool IsDefault { get; set; }
        public string ContactPerson { get; set; }
        public string ContactPhone { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string WarehouseCategoryId { get; set; }
    
        public virtual Spl_WarehouseCategory Spl_WarehouseCategory { get; set; }
        public virtual ICollection<Spl_WarehouseWarrantDetails> Spl_WarehouseWarrantDetails { get; set; }
        public virtual ICollection<Spl_WarehouseWarrant> Spl_WarehouseWarrant { get; set; }
    }
}
