//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Unity.Attributes;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using LinqToExcel;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Data.Entity;
using Apps.IDAL.Flow;
using Apps.Models.Flow;
using Apps.IBLL.Flow;
using Apps.IDAL.Sys;
namespace Apps.BLL.Flow
{
	public partial class Flow_TypeBLL: Virtual_Flow_TypeBLL,IFlow_TypeBLL
	{
        

	}
	public class Virtual_Flow_TypeBLL
	{
        [Dependency]
        public IFlow_TypeRepository m_Rep { get; set; }
		
		[Dependency]
        public ISysUserRepository m_userRep { get; set; }

		[Dependency]
        public ISysStructRepository m_structRep { get; set; }

		public virtual async Task<Tuple<GridPager,List<Flow_TypeModel>>> GetListAsync(GridPager pager, string queryStr)
        {

            IQueryable<Flow_Type> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.Remark.Contains(queryStr)
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
			  
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            List<Flow_TypeModel> list = await CreateModelListAsync(queryData);
            return  new Tuple<GridPager,List<Flow_TypeModel>>(pager,list);
        }
		public virtual async Task<List<Flow_TypeModel>> CreateModelListAsync(IQueryable<Flow_Type> queryData)
        {

            List<Flow_TypeModel> modelList = await (from r in queryData
                                              select new Flow_TypeModel
                                              {
                                                 													Id = r.Id,
													Name = r.Name,
													Remark = r.Remark,
													CreateTime = r.CreateTime,
													Sort = r.Sort,
          

                                              }).ToListAsync();

            return modelList;
        }

		public virtual List<Flow_TypeModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Flow_Type> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.Remark.Contains(queryStr)
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }

			   
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
			public virtual List<Flow_TypeModel> GetListByUserId(ref GridPager pager, string userId,string queryStr)
		{
			return new List<Flow_TypeModel>();
		}
		public virtual List<Flow_TypeModel> GetListByDepId(ref GridPager pager, string depId,string queryStr)
		{
			return new List<Flow_TypeModel>();
		}
		
		public virtual List<Flow_TypeModel> GetListByParentId(ref GridPager pager, string queryStr,object parentId)
        {
			return new List<Flow_TypeModel>();
		}
		public virtual List<Flow_TypeModel> GetList(string id, string parentId)
        {
			return new List<Flow_TypeModel>();
		}
        public virtual List<Flow_TypeModel> CreateModelList(ref IQueryable<Flow_Type> queryData)
        {

            List<Flow_TypeModel> modelList = (from r in queryData
                                              select new Flow_TypeModel
                                              {
													Id = r.Id,
													Name = r.Name,
													Remark = r.Remark,
													CreateTime = r.CreateTime,
													Sort = r.Sort,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Flow_TypeModel model)
        {
            try
            {
                Flow_Type entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Flow_Type();
               				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.Remark = model.Remark;
				entity.CreateTime = model.CreateTime;
				entity.Sort = model.Sort;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		 public virtual async Task<Tuple<ValidationErrors, bool>> CreateAsync(Flow_TypeModel model)
        {
			ValidationErrors errors = new ValidationErrors();
            try
            {
                Flow_Type entity = await m_Rep.GetByIdAsync(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return new Tuple<ValidationErrors, bool>(errors,false);
                }
                entity = new Flow_Type();
               				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.Remark = model.Remark;
				entity.CreateTime = model.CreateTime;
				entity.Sort = model.Sort;
  

                if (await m_Rep.CreateAsync(entity))
                {
                    return new Tuple<ValidationErrors, bool>(errors, true);
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return new Tuple<ValidationErrors, bool>(errors, false);
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
        }

	

		public virtual bool Delete(ref ValidationErrors errors, object id)
        {
            try
            {
                					 if (m_Rep.Delete(id) == 1)
					{
						return true;
					}
					else
					{
						return false;
					}
				  
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, object[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		public virtual async Task<Tuple<ValidationErrors, bool>> DeleteAsync(object[] deleteCollection)
        {
			ValidationErrors errors = new ValidationErrors();
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (await m_Rep.DeleteAsync(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return new Tuple<ValidationErrors, bool>(errors, true);
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            errors.Add("其中有数据删除出错！");
                            return new Tuple<ValidationErrors, bool>(errors, false);
                        }
                    }
                }
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
        }
       

        public virtual bool Edit(ref ValidationErrors errors, Flow_TypeModel model)
        {
            try
            {
                Flow_Type entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.Remark = model.Remark;
				entity.CreateTime = model.CreateTime;
				entity.Sort = model.Sort;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      	 public virtual async Task<Tuple<ValidationErrors, bool>> EditAsync(Flow_TypeModel model)
        {
			ValidationErrors errors = new ValidationErrors();
            try
            {
                Flow_Type entity = await m_Rep.GetByIdAsync(model.Id);
                if (entity == null)
                {
                     errors.Add(Resource.Disable);
                    return new Tuple<ValidationErrors, bool>(errors,false);
                }
                				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.Remark = model.Remark;
				entity.CreateTime = model.CreateTime;
				entity.Sort = model.Sort;
 

                if (await m_Rep.EditAsync(entity))
                {
                    return new Tuple<ValidationErrors, bool>(errors, true);
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return new Tuple<ValidationErrors, bool>(errors, false);
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
        }

        public virtual Flow_TypeModel GetById(object id)
        {
            if (IsExists(id))
            {
                Flow_Type entity = m_Rep.GetById(id);
                Flow_TypeModel model = new Flow_TypeModel();
                              				model.Id = entity.Id;
				model.Name = entity.Name;
				model.Remark = entity.Remark;
				model.CreateTime = entity.CreateTime;
				model.Sort = entity.Sort;
 
                return model;
            }
            else
            {
                return null;
            }
        }

		 public virtual async Task<Flow_TypeModel> GetByIdAsync(object id)
        {
            if (IsExists(id))
            {
                Flow_Type entity = await m_Rep.GetByIdAsync(id);
                Flow_TypeModel model = new Flow_TypeModel();
                              				model.Id = entity.Id;
				model.Name = entity.Name;
				model.Remark = entity.Remark;
				model.CreateTime = entity.CreateTime;
				model.Sort = entity.Sort;
 
                return model;
            }
            else
            {
                return null;
            }
        }

		 /// <summary>
        /// 校验Excel数据,这个方法一般用于重写校验逻辑
        /// </summary>
        public virtual bool CheckImportData(string fileName, List<Flow_TypeModel> list,ref ValidationErrors errors )
        {
          
            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {

                errors.Add("导入的数据文件不存在");
                return false;
            }

            var excelFile = new ExcelQueryFactory(fileName);

            //对应列头
			 				 excelFile.AddMapping<Flow_TypeModel>(x => x.Name, "Name");
				 excelFile.AddMapping<Flow_TypeModel>(x => x.Remark, "Remark");
				 excelFile.AddMapping<Flow_TypeModel>(x => x.CreateTime, "CreateTime");
				 excelFile.AddMapping<Flow_TypeModel>(x => x.Sort, "Sort");
 
            //SheetName
            var excelContent = excelFile.Worksheet<Flow_TypeModel>(0);
            int rowIndex = 1;
            //检查数据正确性
            foreach (var row in excelContent)
            {
                var errorMessage = new StringBuilder();
                var entity = new Flow_TypeModel();
						 				  entity.Id = row.Id;
				  entity.Name = row.Name;
				  entity.Remark = row.Remark;
				  entity.CreateTime = row.CreateTime;
				  entity.Sort = row.Sort;
 
                //=============================================================================
                if (errorMessage.Length > 0)
                {
                    errors.Add(string.Format(
                        "第 {0} 列发现错误：{1}{2}",
                        rowIndex,
                        errorMessage,
                        "<br/>"));
                }
                list.Add(entity);
                rowIndex += 1;
            }
            if (errors.Count > 0)
            {
                return false;
            }
            return true;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        public virtual void SaveImportData(IEnumerable<Flow_TypeModel> list)
        {
            try
            {
                using (DBContainer db = new DBContainer())
                {
                    foreach (var model in list)
                    {
                        Flow_Type entity = new Flow_Type();
                       						entity.Id = ResultHelper.NewId;
						entity.Name = model.Name;
						entity.Remark = model.Remark;
						entity.CreateTime = ResultHelper.NowTime;
						entity.Sort = model.Sort;
 
                        db.Flow_Type.Add(entity);
                    }
                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
		public virtual bool Check(ref ValidationErrors errors, object id,int flag)
        {
			return true;
		}

        public virtual bool IsExists(object id)
        {
            return m_Rep.IsExist(id);
        }
		
		public void Dispose()
        { 
            
        }

	}
}
