//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Unity.Attributes;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using LinqToExcel;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Data.Entity;
using Apps.IDAL.Flow;
using Apps.Models.Flow;
using Apps.IBLL.Flow;
using Apps.IDAL.Sys;
namespace Apps.BLL.Flow
{
	public partial class Flow_FormAttrBLL: Virtual_Flow_FormAttrBLL,IFlow_FormAttrBLL
	{
        

	}
	public class Virtual_Flow_FormAttrBLL
	{
        [Dependency]
        public IFlow_FormAttrRepository m_Rep { get; set; }
		
		[Dependency]
        public ISysUserRepository m_userRep { get; set; }

		[Dependency]
        public ISysStructRepository m_structRep { get; set; }

		public virtual async Task<Tuple<GridPager,List<Flow_FormAttrModel>>> GetListAsync(GridPager pager, string queryStr)
        {

            IQueryable<Flow_FormAttr> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Title.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.AttrType.Contains(queryStr)
								|| a.CheckRule.Contains(queryStr)
								|| a.CheckJS.Contains(queryStr)
								|| a.TypeId.Contains(queryStr)
								
								|| a.OptionList.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
			  
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            List<Flow_FormAttrModel> list = await CreateModelListAsync(queryData);
            return  new Tuple<GridPager,List<Flow_FormAttrModel>>(pager,list);
        }
		public virtual async Task<List<Flow_FormAttrModel>> CreateModelListAsync(IQueryable<Flow_FormAttr> queryData)
        {

            List<Flow_FormAttrModel> modelList = await (from r in queryData
                                              select new Flow_FormAttrModel
                                              {
                                                 													Id = r.Id,
													Title = r.Title,
													Name = r.Name,
													AttrType = r.AttrType,
													CheckRule = r.CheckRule,
													CheckJS = r.CheckJS,
													TypeId = r.TypeId,
													CreateTime = r.CreateTime,
													OptionList = r.OptionList,
          

                                              }).ToListAsync();

            return modelList;
        }

		public virtual List<Flow_FormAttrModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Flow_FormAttr> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Title.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.AttrType.Contains(queryStr)
								|| a.CheckRule.Contains(queryStr)
								|| a.CheckJS.Contains(queryStr)
								|| a.TypeId.Contains(queryStr)
								
								|| a.OptionList.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }

			   
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
			public virtual List<Flow_FormAttrModel> GetListByUserId(ref GridPager pager, string userId,string queryStr)
		{
			return new List<Flow_FormAttrModel>();
		}
		public virtual List<Flow_FormAttrModel> GetListByDepId(ref GridPager pager, string depId,string queryStr)
		{
			return new List<Flow_FormAttrModel>();
		}
		
		public virtual List<Flow_FormAttrModel> GetListByParentId(ref GridPager pager, string queryStr,object parentId)
        {
			return new List<Flow_FormAttrModel>();
		}
		public virtual List<Flow_FormAttrModel> GetList(string id, string parentId)
        {
			return new List<Flow_FormAttrModel>();
		}
        public virtual List<Flow_FormAttrModel> CreateModelList(ref IQueryable<Flow_FormAttr> queryData)
        {

            List<Flow_FormAttrModel> modelList = (from r in queryData
                                              select new Flow_FormAttrModel
                                              {
													Id = r.Id,
													Title = r.Title,
													Name = r.Name,
													AttrType = r.AttrType,
													CheckRule = r.CheckRule,
													CheckJS = r.CheckJS,
													TypeId = r.TypeId,
													CreateTime = r.CreateTime,
													OptionList = r.OptionList,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Flow_FormAttrModel model)
        {
            try
            {
                Flow_FormAttr entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Flow_FormAttr();
               				entity.Id = model.Id;
				entity.Title = model.Title;
				entity.Name = model.Name;
				entity.AttrType = model.AttrType;
				entity.CheckRule = model.CheckRule;
				entity.CheckJS = model.CheckJS;
				entity.TypeId = model.TypeId;
				entity.CreateTime = model.CreateTime;
				entity.OptionList = model.OptionList;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		 public virtual async Task<Tuple<ValidationErrors, bool>> CreateAsync(Flow_FormAttrModel model)
        {
			ValidationErrors errors = new ValidationErrors();
            try
            {
                Flow_FormAttr entity = await m_Rep.GetByIdAsync(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return new Tuple<ValidationErrors, bool>(errors,false);
                }
                entity = new Flow_FormAttr();
               				entity.Id = model.Id;
				entity.Title = model.Title;
				entity.Name = model.Name;
				entity.AttrType = model.AttrType;
				entity.CheckRule = model.CheckRule;
				entity.CheckJS = model.CheckJS;
				entity.TypeId = model.TypeId;
				entity.CreateTime = model.CreateTime;
				entity.OptionList = model.OptionList;
  

                if (await m_Rep.CreateAsync(entity))
                {
                    return new Tuple<ValidationErrors, bool>(errors, true);
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return new Tuple<ValidationErrors, bool>(errors, false);
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
        }

	

		public virtual bool Delete(ref ValidationErrors errors, object id)
        {
            try
            {
                					 if (m_Rep.Delete(id) == 1)
					{
						return true;
					}
					else
					{
						return false;
					}
				  
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, object[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		public virtual async Task<Tuple<ValidationErrors, bool>> DeleteAsync(object[] deleteCollection)
        {
			ValidationErrors errors = new ValidationErrors();
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (await m_Rep.DeleteAsync(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return new Tuple<ValidationErrors, bool>(errors, true);
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            errors.Add("其中有数据删除出错！");
                            return new Tuple<ValidationErrors, bool>(errors, false);
                        }
                    }
                }
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
        }
       

        public virtual bool Edit(ref ValidationErrors errors, Flow_FormAttrModel model)
        {
            try
            {
                Flow_FormAttr entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.Title = model.Title;
				entity.Name = model.Name;
				entity.AttrType = model.AttrType;
				entity.CheckRule = model.CheckRule;
				entity.CheckJS = model.CheckJS;
				entity.TypeId = model.TypeId;
				entity.CreateTime = model.CreateTime;
				entity.OptionList = model.OptionList;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      	 public virtual async Task<Tuple<ValidationErrors, bool>> EditAsync(Flow_FormAttrModel model)
        {
			ValidationErrors errors = new ValidationErrors();
            try
            {
                Flow_FormAttr entity = await m_Rep.GetByIdAsync(model.Id);
                if (entity == null)
                {
                     errors.Add(Resource.Disable);
                    return new Tuple<ValidationErrors, bool>(errors,false);
                }
                				entity.Id = model.Id;
				entity.Title = model.Title;
				entity.Name = model.Name;
				entity.AttrType = model.AttrType;
				entity.CheckRule = model.CheckRule;
				entity.CheckJS = model.CheckJS;
				entity.TypeId = model.TypeId;
				entity.CreateTime = model.CreateTime;
				entity.OptionList = model.OptionList;
 

                if (await m_Rep.EditAsync(entity))
                {
                    return new Tuple<ValidationErrors, bool>(errors, true);
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return new Tuple<ValidationErrors, bool>(errors, false);
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
        }

        public virtual Flow_FormAttrModel GetById(object id)
        {
            if (IsExists(id))
            {
                Flow_FormAttr entity = m_Rep.GetById(id);
                Flow_FormAttrModel model = new Flow_FormAttrModel();
                              				model.Id = entity.Id;
				model.Title = entity.Title;
				model.Name = entity.Name;
				model.AttrType = entity.AttrType;
				model.CheckRule = entity.CheckRule;
				model.CheckJS = entity.CheckJS;
				model.TypeId = entity.TypeId;
				model.CreateTime = entity.CreateTime;
				model.OptionList = entity.OptionList;
 
                return model;
            }
            else
            {
                return null;
            }
        }

		 public virtual async Task<Flow_FormAttrModel> GetByIdAsync(object id)
        {
            if (IsExists(id))
            {
                Flow_FormAttr entity = await m_Rep.GetByIdAsync(id);
                Flow_FormAttrModel model = new Flow_FormAttrModel();
                              				model.Id = entity.Id;
				model.Title = entity.Title;
				model.Name = entity.Name;
				model.AttrType = entity.AttrType;
				model.CheckRule = entity.CheckRule;
				model.CheckJS = entity.CheckJS;
				model.TypeId = entity.TypeId;
				model.CreateTime = entity.CreateTime;
				model.OptionList = entity.OptionList;
 
                return model;
            }
            else
            {
                return null;
            }
        }

		 /// <summary>
        /// 校验Excel数据,这个方法一般用于重写校验逻辑
        /// </summary>
        public virtual bool CheckImportData(string fileName, List<Flow_FormAttrModel> list,ref ValidationErrors errors )
        {
          
            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {

                errors.Add("导入的数据文件不存在");
                return false;
            }

            var excelFile = new ExcelQueryFactory(fileName);

            //对应列头
			 				 excelFile.AddMapping<Flow_FormAttrModel>(x => x.Title, "Title");
				 excelFile.AddMapping<Flow_FormAttrModel>(x => x.Name, "Name");
				 excelFile.AddMapping<Flow_FormAttrModel>(x => x.AttrType, "AttrType");
				 excelFile.AddMapping<Flow_FormAttrModel>(x => x.CheckRule, "CheckRule");
				 excelFile.AddMapping<Flow_FormAttrModel>(x => x.CheckJS, "CheckJS");
				 excelFile.AddMapping<Flow_FormAttrModel>(x => x.TypeId, "TypeId");
				 excelFile.AddMapping<Flow_FormAttrModel>(x => x.CreateTime, "CreateTime");
				 excelFile.AddMapping<Flow_FormAttrModel>(x => x.OptionList, "OptionList");
 
            //SheetName
            var excelContent = excelFile.Worksheet<Flow_FormAttrModel>(0);
            int rowIndex = 1;
            //检查数据正确性
            foreach (var row in excelContent)
            {
                var errorMessage = new StringBuilder();
                var entity = new Flow_FormAttrModel();
						 				  entity.Id = row.Id;
				  entity.Title = row.Title;
				  entity.Name = row.Name;
				  entity.AttrType = row.AttrType;
				  entity.CheckRule = row.CheckRule;
				  entity.CheckJS = row.CheckJS;
				  entity.TypeId = row.TypeId;
				  entity.CreateTime = row.CreateTime;
				  entity.OptionList = row.OptionList;
 
                //=============================================================================
                if (errorMessage.Length > 0)
                {
                    errors.Add(string.Format(
                        "第 {0} 列发现错误：{1}{2}",
                        rowIndex,
                        errorMessage,
                        "<br/>"));
                }
                list.Add(entity);
                rowIndex += 1;
            }
            if (errors.Count > 0)
            {
                return false;
            }
            return true;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        public virtual void SaveImportData(IEnumerable<Flow_FormAttrModel> list)
        {
            try
            {
                using (DBContainer db = new DBContainer())
                {
                    foreach (var model in list)
                    {
                        Flow_FormAttr entity = new Flow_FormAttr();
                       						entity.Id = ResultHelper.NewId;
						entity.Title = model.Title;
						entity.Name = model.Name;
						entity.AttrType = model.AttrType;
						entity.CheckRule = model.CheckRule;
						entity.CheckJS = model.CheckJS;
						entity.TypeId = model.TypeId;
						entity.CreateTime = ResultHelper.NowTime;
						entity.OptionList = model.OptionList;
 
                        db.Flow_FormAttr.Add(entity);
                    }
                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
		public virtual bool Check(ref ValidationErrors errors, object id,int flag)
        {
			return true;
		}

        public virtual bool IsExists(object id)
        {
            return m_Rep.IsExist(id);
        }
		
		public void Dispose()
        { 
            
        }

	}
}
