//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Unity.Attributes;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using LinqToExcel;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Data.Entity;
using Apps.IDAL.Sys;
using Apps.Models.Sys;
using Apps.IBLL.Sys;

namespace Apps.BLL.Sys
{
	public partial class SysValidTokenBLL: Virtual_SysValidTokenBLL,ISysValidTokenBLL
	{
        

	}
	public class Virtual_SysValidTokenBLL
	{
        [Dependency]
        public ISysValidTokenRepository m_Rep { get; set; }
		
		[Dependency]
        public ISysUserRepository m_userRep { get; set; }

		[Dependency]
        public ISysStructRepository m_structRep { get; set; }

		public virtual async Task<Tuple<GridPager,List<SysValidTokenModel>>> GetListAsync(GridPager pager, string queryStr)
        {

            IQueryable<SysValidToken> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Token.Contains(queryStr)
								
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
			  
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            List<SysValidTokenModel> list = await CreateModelListAsync(queryData);
            return  new Tuple<GridPager,List<SysValidTokenModel>>(pager,list);
        }
		public virtual async Task<List<SysValidTokenModel>> CreateModelListAsync(IQueryable<SysValidToken> queryData)
        {

            List<SysValidTokenModel> modelList = await (from r in queryData
                                              select new SysValidTokenModel
                                              {
                                                 													Id = r.Id,
													Token = r.Token,
													OverTime = r.OverTime,
													ModifyTime = r.ModifyTime,
													CreateTime = r.CreateTime,
          

                                              }).ToListAsync();

            return modelList;
        }

		public virtual List<SysValidTokenModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysValidToken> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Token.Contains(queryStr)
								
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }

			   
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
			public virtual List<SysValidTokenModel> GetListByUserId(ref GridPager pager, string userId,string queryStr)
		{
			return new List<SysValidTokenModel>();
		}
		public virtual List<SysValidTokenModel> GetListByDepId(ref GridPager pager, string depId,string queryStr)
		{
			return new List<SysValidTokenModel>();
		}
		
		public virtual List<SysValidTokenModel> GetListByParentId(ref GridPager pager, string queryStr,object parentId)
        {
			return new List<SysValidTokenModel>();
		}
		public virtual List<SysValidTokenModel> GetList(string id, string parentId)
        {
			return new List<SysValidTokenModel>();
		}
        public virtual List<SysValidTokenModel> CreateModelList(ref IQueryable<SysValidToken> queryData)
        {

            List<SysValidTokenModel> modelList = (from r in queryData
                                              select new SysValidTokenModel
                                              {
													Id = r.Id,
													Token = r.Token,
													OverTime = r.OverTime,
													ModifyTime = r.ModifyTime,
													CreateTime = r.CreateTime,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysValidTokenModel model)
        {
            try
            {
                SysValidToken entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysValidToken();
               				entity.Id = model.Id;
				entity.Token = model.Token;
				entity.OverTime = model.OverTime;
				entity.ModifyTime = model.ModifyTime;
				entity.CreateTime = model.CreateTime;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		 public virtual async Task<Tuple<ValidationErrors, bool>> CreateAsync(SysValidTokenModel model)
        {
			ValidationErrors errors = new ValidationErrors();
            try
            {
                SysValidToken entity = await m_Rep.GetByIdAsync(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return new Tuple<ValidationErrors, bool>(errors,false);
                }
                entity = new SysValidToken();
               				entity.Id = model.Id;
				entity.Token = model.Token;
				entity.OverTime = model.OverTime;
				entity.ModifyTime = model.ModifyTime;
				entity.CreateTime = model.CreateTime;
  

                if (await m_Rep.CreateAsync(entity))
                {
                    return new Tuple<ValidationErrors, bool>(errors, true);
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return new Tuple<ValidationErrors, bool>(errors, false);
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
        }

	

		public virtual bool Delete(ref ValidationErrors errors, object id)
        {
            try
            {
                					 if (m_Rep.Delete(id) == 1)
					{
						return true;
					}
					else
					{
						return false;
					}
				  
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, object[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		public virtual async Task<Tuple<ValidationErrors, bool>> DeleteAsync(object[] deleteCollection)
        {
			ValidationErrors errors = new ValidationErrors();
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (await m_Rep.DeleteAsync(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return new Tuple<ValidationErrors, bool>(errors, true);
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            errors.Add("其中有数据删除出错！");
                            return new Tuple<ValidationErrors, bool>(errors, false);
                        }
                    }
                }
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
        }
       

        public virtual bool Edit(ref ValidationErrors errors, SysValidTokenModel model)
        {
            try
            {
                SysValidToken entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.Token = model.Token;
				entity.OverTime = model.OverTime;
				entity.ModifyTime = model.ModifyTime;
				entity.CreateTime = model.CreateTime;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      	 public virtual async Task<Tuple<ValidationErrors, bool>> EditAsync(SysValidTokenModel model)
        {
			ValidationErrors errors = new ValidationErrors();
            try
            {
                SysValidToken entity = await m_Rep.GetByIdAsync(model.Id);
                if (entity == null)
                {
                     errors.Add(Resource.Disable);
                    return new Tuple<ValidationErrors, bool>(errors,false);
                }
                				entity.Id = model.Id;
				entity.Token = model.Token;
				entity.OverTime = model.OverTime;
				entity.ModifyTime = model.ModifyTime;
				entity.CreateTime = model.CreateTime;
 

                if (await m_Rep.EditAsync(entity))
                {
                    return new Tuple<ValidationErrors, bool>(errors, true);
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return new Tuple<ValidationErrors, bool>(errors, false);
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return new Tuple<ValidationErrors, bool>(errors, false);
            }
        }

        public virtual SysValidTokenModel GetById(object id)
        {
            if (IsExists(id))
            {
                SysValidToken entity = m_Rep.GetById(id);
                SysValidTokenModel model = new SysValidTokenModel();
                              				model.Id = entity.Id;
				model.Token = entity.Token;
				model.OverTime = entity.OverTime;
				model.ModifyTime = entity.ModifyTime;
				model.CreateTime = entity.CreateTime;
 
                return model;
            }
            else
            {
                return null;
            }
        }

		 public virtual async Task<SysValidTokenModel> GetByIdAsync(object id)
        {
            if (IsExists(id))
            {
                SysValidToken entity = await m_Rep.GetByIdAsync(id);
                SysValidTokenModel model = new SysValidTokenModel();
                              				model.Id = entity.Id;
				model.Token = entity.Token;
				model.OverTime = entity.OverTime;
				model.ModifyTime = entity.ModifyTime;
				model.CreateTime = entity.CreateTime;
 
                return model;
            }
            else
            {
                return null;
            }
        }

		 /// <summary>
        /// 校验Excel数据,这个方法一般用于重写校验逻辑
        /// </summary>
        public virtual bool CheckImportData(string fileName, List<SysValidTokenModel> list,ref ValidationErrors errors )
        {
          
            var targetFile = new FileInfo(fileName);

            if (!targetFile.Exists)
            {

                errors.Add("导入的数据文件不存在");
                return false;
            }

            var excelFile = new ExcelQueryFactory(fileName);

            //对应列头
			 				 excelFile.AddMapping<SysValidTokenModel>(x => x.Token, "Token");
				 excelFile.AddMapping<SysValidTokenModel>(x => x.OverTime, "OverTime");
				 excelFile.AddMapping<SysValidTokenModel>(x => x.ModifyTime, "ModifyTime");
				 excelFile.AddMapping<SysValidTokenModel>(x => x.CreateTime, "CreateTime");
 
            //SheetName
            var excelContent = excelFile.Worksheet<SysValidTokenModel>(0);
            int rowIndex = 1;
            //检查数据正确性
            foreach (var row in excelContent)
            {
                var errorMessage = new StringBuilder();
                var entity = new SysValidTokenModel();
						 				  entity.Id = row.Id;
				  entity.Token = row.Token;
				  entity.OverTime = row.OverTime;
				  entity.ModifyTime = row.ModifyTime;
				  entity.CreateTime = row.CreateTime;
 
                //=============================================================================
                if (errorMessage.Length > 0)
                {
                    errors.Add(string.Format(
                        "第 {0} 列发现错误：{1}{2}",
                        rowIndex,
                        errorMessage,
                        "<br/>"));
                }
                list.Add(entity);
                rowIndex += 1;
            }
            if (errors.Count > 0)
            {
                return false;
            }
            return true;
        }

        /// <summary>
        /// 保存数据
        /// </summary>
        public virtual void SaveImportData(IEnumerable<SysValidTokenModel> list)
        {
            try
            {
                using (DBContainer db = new DBContainer())
                {
                    foreach (var model in list)
                    {
                        SysValidToken entity = new SysValidToken();
                       						entity.Id = ResultHelper.NewId;
						entity.Token = model.Token;
						entity.OverTime = model.OverTime;
						entity.ModifyTime = model.ModifyTime;
						entity.CreateTime = ResultHelper.NowTime;
 
                        db.SysValidToken.Add(entity);
                    }
                    db.SaveChanges();
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
		public virtual bool Check(ref ValidationErrors errors, object id,int flag)
        {
			return true;
		}

        public virtual bool IsExists(object id)
        {
            return m_Rep.IsExist(id);
        }
		
		public void Dispose()
        { 
            
        }

	}
}
